version: '3'

services:
  nav-website:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/cocotina2023/nav-website:latest
    container_name: nav-website
    ports:
      - "4500:4500"
    environment:
      NODE_ENV: production
      PORT: 4500
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123456
      JWT_SECRET: replace-with-strong-secret
      CORS_ORIGINS: "*"
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4500/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
