version: '3'

services:
  nav-website:
    image: ghcr.io/cocotina2023/nav-website:latest
    container_name: nav-website
    ports:
      - "4500:4500"                        # 主机端口:容器端口
    environment:
      - NODE_ENV=production                # 运行模式
      - PORT=4500                          # 容器内部 Node.js 监听端口
      - ADMIN_USERNAME=admin               # 默认管理员账号
      - ADMIN_PASSWORD=123456              # 默认管理员密码
    volumes:
      - ./database:/app/database           # 持久化 SQLite 数据库
      - ./uploads:/app/uploads             # 持久化上传文件
    restart: unless-stopped                # 异常退出自动重启

